name: realdex_pour

task_name: panda_pick_place

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    img:
      shape: [3, 84, 84]
      type: rgb
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [8]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.realdex_dataset_dp.RealDexDatasetDP
  zarr_path: data/11-02/pick_place_d455.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
